import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { TailAdminProviders } from "@tailadmin/providers";
import { DEFAULT_LOCALE, LOCALE_COOKIE_NAME } from "@/src/lib/locale/constants";
import { normalizeLocale } from "@/src/lib/locale/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-tailadmin-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const localeCookie = cookieStore.get(LOCALE_COOKIE_NAME)?.value;
  const initialLocale = normalizeLocale(localeCookie ?? DEFAULT_LOCALE);

  return (
    <html lang={initialLocale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased`}
      >
        <TailAdminProviders initialLocale={initialLocale}>{children}</TailAdminProviders>
      </body>
    </html>
  );
}
